import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/footer/Footer";

const Home: NextPage = () => {
	return (
		<div className={`wrapper`}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={`container`}>
				<h1 className={``}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
			</main>

			<Footer />
		</div>
	);
};

export default Home;
